music/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from music import views, move_csv
#from music import mdgCrawling

app_name = 'music'

urlpatterns = [
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('postlist/', views.PostListView.as_view(), name='post_list'),
    path('mdglist/', views.MDGListView.as_view(), name='mdg_list'),
    path('mdglist/delete/', views.MDGDelete, name="mdg_delete"),
    #path('mdglist/delete/<int:randuser>', views_re.MDGDelete, name="mdg_delete"),
    #path('mdglist/delete/<int:pk>', views.MDGDelete, name="mdg_delete"),
    path('', views.SiteMain, name='SiteMain'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/write', views.post_write, name='post_write'),
    path('post/update/<int:pk>', views.post_update, name='post_update'),
    path('post/delete/<int:pk>', views.PostDeleteView.as_view(), name='post_delete'),
    path('mdgget/', views.mdg_get, name='mdg_get'),
    path('mdgup/', views.mdg_up, name='mdg_up'),
    #path('result/', move_csv.move_to_genie, name='result'),
    path('re_result/', views.Recmd, name='re_result'),
    path('post/<int:pk>/comment/', views.comment_write, name='comment_write'),
    path('post/download/<int:pk>', views.post_download_view, name="post_download"),
    path('user_guide/', views.user_guide, name="user_guide"),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.urls import reverse
from uuid import uuid4
from datetime import datetime

class Mdg(models.Model):
    music_pk = models.AutoField(db_column='Music_pk', primary_key=True)  # Field name made lowercase.
    user_num = models.IntegerField(db_column='User_num')  # Field name made lowercase.
    artist = models.CharField(max_length=100)
    song = models.CharField(max_length=100)
    album = models.CharField(max_length=100)
    Site_Code = (
        ('M', 'Melon'),
        ('B', 'Bugs'),
        ('G', 'Genie'),
        ('F', 'FLO'),
        ('V', 'Vibe')
    )
    site_code = models.CharField(max_length=1, choices=Site_Code )
    genre = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'MDG'




class MdIntegratedM(models.Model):
    music_pk = models.AutoField(db_column='Music_pk', primary_key=True)  # Field name made lowercase.
    in_artist = models.CharField(max_length=50)
    in_song = models.CharField(max_length=50)
    in_album = models.CharField(max_length=100)
    in_genre = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'MD_integrated_m'

def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    return '/'.join(['post_file/', ymd_path, uuid_name])


class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    writer = models.CharField(max_length=100)
    password = models.IntegerField()
    post_date = models.DateTimeField(auto_now_add=True)
    post_title = models.CharField(max_length=45)
    post_contents = models.TextField(blank=True)
    post_like = models.IntegerField(default=0)
    post_hit = models.IntegerField(default=0)
    post_file = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    post_filename = models.CharField(max_length=100, null=True, verbose_name='첨부파일명')

    Table_num = (
        ('0', '국내'),
        ('1', '해외'),
        ('2', '기타'),
    )
    table_num = models.CharField(max_length=1, choices=Table_num)

    class Meta:
        managed = False
        db_table = 'Post'
        ordering = ['-post_id']

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('music:post_detail', args=[str(self.post_id)])

    def get_previous(self):
        return self.get_previous_by_post_date()

    def get_next(self):
        return self.get_next_by_post_date()




class Comment(models.Model):
    com_id = models.AutoField(primary_key=True)
    com_writer = models.CharField(max_length=100)
    com_password = models.IntegerField(default=0)     #비밀번호 일단 구현x
    com_date = models.DateTimeField(auto_now_add=True)
    com_contents = models.CharField(max_length=200)
    com_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')

    class Meta:
        managed = False
        db_table = 'comment'
        ordering = ['-com_id']

music/forms.py
from django import forms
from .models import Post

class CreatePostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)
        self.fields['post_title'].label = '제목'
        self.fields['post_title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control',
            'autofocus': True,
        })
        self.fields['table_num'].widget.attrs.update({

            'class': 'form-control',
            'placeholder': '장르선택',
        })

    class Meta:
        model = Post
        fields = ['table_num', 'writer', 'password', 'post_title',  'post_contents', 'post_file']

        widgets = {
            'writer': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}),
            # 'table_num': forms.TextInput(attrs={'class': 'form-control'}),
            'post_contents' : forms.Textarea(attrs={'class': 'form-control', 'placeholder': '내용을 입력해주세요.'}),
            'post_file' : forms.FileInput(attrs={'class': 'form-control', 'size': '20'}),

        }
        labels = {
            'username': '닉네임',
            'email': '이메일',
            'password': '패스워드'
        }

music/views.py
import os
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.urls import reverse_lazy
from django.views import generic
from .forms import CreatePostForm
from .models import Post, Comment, Mdg, MdIntegratedM
from django.contrib import messages
import datetime, random
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
import urllib
import mimetypes
from . import move_csv, new_crawling


class MDGListView(generic.ListView):
    model = Mdg
    context_object_name = 'mdgs'


class AgreementView(generic.View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'music/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True

            if request.POST.get('yes'):
                return HttpResponse('<script type="text/javascript">window.close()</script>')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'music/agreement.html')

def MDGDelete(request):
    selected = Mdg.objects.all()
    putmusic = MdIntegratedM.objects.all()
    count = 0
    for i in range(len(selected)): # MdIntegratedM에 데이터 저장 및 중복 확인
        for j in range(len(putmusic)):
            if putmusic[j].in_song == selected[i].song and putmusic[j].in_album == selected[i].album and selected[i].site_code == 'M':
                #print(selected[i].song, selected[i].site_code)
                count += 1
        if count == 0 and selected[i].site_code == 'M':
            MdIntegratedM.objects.create(in_artist=selected[i].artist, in_song=selected[i].song, in_album = selected[i].album, in_genre=selected[i].genre)
           # print(selected[i].song, selected[i].site_code)
        count = 0

    selected.delete()
    return redirect('music:SiteMain')


def mdg_get(request):
    #url = request.POST.get('url')
    id = request.POST.get('id')
    password = request.POST.get('password')
    site = request.POST.get('site')
    #randuser = new_crawling.get_music(site, id, password)
    context = {'randusers': new_crawling.get_music(site, id, password)}
    print(context)
    #return render(request, 'music/mdg_list.html', context)
    return redirect('music:mdg_list')



def mdg_up(request):
    if request.FILES.__len__() == 0:
        message = "no file."
        return JsonResponse({"message": message})
    uploadFile = request.FILES['file'];
    # csv파일이 아니라면 작업을 멈추고 리턴합니다.
    if uploadFile.name.find('csv') < 0:
        message = "wrong file"
        return JsonResponse({"message": message})
    read = uploadFile.read().decode('UTF-8')
    # 줄바꿈이 생기는 것을 기준으로 배열
    list = []
    id = request.POST.get('id')
    password = request.POST.get('password')
    site = request.POST.get('site')
    readLine = read.split('\r\r\n')
    for line in readLine:
        list.append([line.replace("\\", " - ")])
    if site == 'genie':
        context = {'notfounds': move_csv.move_to_genie(id, password, list)}
        return render(request, 'music/result.html', context)
    if site == 'melon':
        context = {'notfounds': move_csv.move_to_melon(id, password, list)}
        return render(request, 'music/result.html', context)
    if site == 'flo':
        context = {'notfounds': move_csv.move_to_flo(id, password, list)}
        return render(request, 'music/result.html', context)
    if site == 'bugs':
        context = {'notfounds': move_csv.move_to_bugs(id, password, list)}
        return render(request, 'music/result.html', context)
    if site == 'vibe':
        context = {'notfounds': move_csv.move_to_vibe(id, password, list)}
        return render(request, 'music/result.html', context)
    else:
        return redirect('music:SiteMain')


class PostListView(generic.ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 10


class PostDetailView(generic.DetailView):
    model = Post


class PostDeleteView(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('music:post_list')


def post_write(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            if request.FILES:
                if 'post_file' in request.FILES.keys():
                    post.post_filename = request.FILES['post_file'].name
                    if post.post_filename.find('csv') < 0:
                        title = post.post_title
                        content = post.post_contents
                        name = post.writer
                        password = post.password
                        table_num = post.table_num
                        form = CreatePostForm(initial={'post_title': title, 'post_contents': content, 'writer': name, 'password': password, 'table_num': table_num, })
                        return render(request, 'music/write_post.html', {'form': form})

            post.save()
            return redirect('music:post_list')
    else:
        form = CreatePostForm()
    return render(request, 'music/write_post.html', {'form': form})


def post_update(request, pk):
    post = get_object_or_404(Post, pk = pk)
    if request.method == 'POST':
        context = {'post' : post, }
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        #old_password = post.password
        #form_old = CreatePostForm(initial={'password': old_password, })
        #form.password = request.password

        #if form.password != form_old.password:
        #    messages.info(request, 'you are not allowed')
        #    return HttpResponseRedirect(reverse_lazy('music:post_list'))

        if form.is_valid():
            post = form.save(commit=False)
            if request.FILES:
                if 'post_file' in request.FILES.keys():
                    post.post_filename = request.FILES['post_file'].name
                    if post.post_filename.find('csv') < 0:
                        title = post.post_title
                        content = post.post_contents
                        name = post.writer
                        password = post.password
                        table_num = post.table_num
                        form = CreatePostForm(initial={'post_title': title, 'post_contents': content, 'writer': name, 'password': password, 'table_num': table_num, })
                        return render(request, 'music/write_post.html', {'form': form})
            post.post_date = datetime.datetime.now()
            post.save()
            return render(request, 'music/post_detail.html', context=context )
    else:
        title = post.post_title
        content = post.post_contents
        name = post.writer
        password = post.password
        table_num = post.table_num
        form = CreatePostForm(initial={'post_title': title, 'post_contents': content, 'writer': name, 'password': password, 'table_num': table_num, })
    return render(request, 'music/write_post.html', {'form': form})


def comment_write(request, pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=pk)
        content = request.POST.get('content')
       # password = request.POST.get('password')
        writer = request.POST.get('writer')

        Comment.objects.create(com_post=post, com_writer=writer, com_contents=content)  # com_password=password,
        return HttpResponseRedirect(resolve_url('music:post_detail', pk=post.pk))


def post_download_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    url = 'media/'+post.post_file.decode("utf-8")
    file_url = urllib.parse.unquote(url)
    #print(file_url, 999)

    if os.path.exists(file_url):
        with open(file_url, 'rb') as fh:
            quote_file_url = urllib.parse.quote(post.post_filename.encode('utf-8'))
            response = HttpResponse(fh.read(), content_type=mimetypes.guess_type(file_url)[0])
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404


def SiteMain(request):
    return render(request, 'music/SiteMain.html')


def Recmd(request):
    re_genre = request.POST.get('re_genre').upper()
    #print(re_genre)
    get_indb = MdIntegratedM.objects.all()
    recmds=[]
    if re_genre == '알앤비':
        re_genre = 'R&B'
    if re_genre == 'JAZZ':
        re_genre = '재즈'
    if re_genre == 'OST':
        re_kor_m = '국내영화'
        re_fore_m = '해외영화'
        re_kor_d = '국내드라마'
        re_fore_d = '해외드라마'
        for i in range(len(get_indb)):
            if re_kor_m in get_indb[i].in_genre or re_fore_m in get_indb[i].in_genre or re_kor_d in get_indb[i].in_genre or re_fore_d in get_indb[i].in_genre:
                recmds.append(get_indb[i].in_song + ' - ' + get_indb[i].in_artist + ', [' + get_indb[i].in_genre + ']')
        if len(recmds) > 10:
            randomList = random.sample(recmds, 10)
            #for recmd in randomList:
                #print(recmd)
            context = {'recmds': randomList}
            return render(request, 'music/re_result.html', context)
        elif len(recmds) == 0:
            recmds.append('선택한 장르의 곡들이 없습니다.')
            context = {'recmds': recmds}
            return render(request, 'music/re_result.html', context)
        else:
            #for recmd in recmds:
                #print(recmd)
            context = {'recmds': recmds}
            return render(request, 'music/re_result.html', context)
    else:
        for i in range(len(get_indb)):
            if re_genre in get_indb[i].in_genre.upper():
                recmds.append(get_indb[i].in_song + ' - ' + get_indb[i].in_artist + ', [' + get_indb[i].in_genre + ']')
        if len(recmds) > 10:
            randomList = random.sample(recmds, 10)
            #for recmd in randomList:

templates/music/SiteMain.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>It's time's music_move 홈페이지</title>
    <link rel="stylesheet" type="text/css" href="{% static 'music/default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/home.css' %}">


</head>

<body>
    <div class="nav">
        <div class="nav-area">
            <div class="nav-left">
                <a href="" style="margin: 0% 200% 0% -200%">
                    <img src="{% static 'music/img/logo.png' %}" style="width: 96px; height: auto; position: -ms-device-fixed" alt="logo">
                </a>
            </div>
            <div class="nav-right">
                <ul>
                    <li><a href="{% url 'music:user_guide' %}">사용 설명</a></li>
                    <li><a href="{% url 'music:post_list' %}">공유 게시판</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="nav-bar"></div>
    
    
    <main class="main">
        <div class="main__info"style="margin: 40% 0% 0% 30%">
            <hgriup class="main__titles">
                <br><br><br><br>
                <h6 class="main__pre-title"style="margin: 0% 0% 0% 30%">뮤직 플레이 리스트 저장 및 변환 웹페이지입니다.</h6>
                <h2 class="main__title">Music Site</h2>
                <h5 class="main__subtitle"style="margin: 0% 0% 0% 35%">잇츠타임팀의 웹페이지를 보고 계십니다.</h5>
            </hgriup>
        </div>

    <div class="get-information" style="margin: 35% 0% 0% 75%">
        <div class="get-1" style="background-color: transparent;">
         <div class="get-all" style="position: relative; width: 200%; background-color: transparent;">
             <ul class="get-url">
                 <form action="mdgget/" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    <input type="text" name="id" size=35 class="frm_input required" size="35" maxLength="35" placeholder="사이트 아이디 입력"><br>
                    <input type="password" name="password" size=35 class="frm_input required" size="35" maxLength="35" placeholder="사이트 비밀번호 입력"><br>
                    <label><input type="radio" name="site" value="melon"> Melon</label>
                    <label><input type="radio" name="site" value="genie"> Genie</label>
                    <label><input type="radio" name="site" value="bugs"> Bugs</label>
                    <label><input type="radio" name="site" value="flo"> FLO</label>
                    <label><input type="radio" name="site" value="vibe"> VIBE</label>
                    <input type="submit" value="  플레이 리스트 추출하기  " class="btn_submit" style="padding: 10px; height: 40px; margin: 2% 0% 0% 45%;">
                </form>
                        <form method="get" enctype="multipart/form-data">
                            <button
                                    class="btn-terms"
                                    style="padding: 10px;
                                            height: 40px;
                                            width: 40%;
                                            margin: 2% 0% 0% 56%;
                                            background-color: #4b545e;
                                            color: white;
                                            border: none;"
                                    onclick="window.open('agreement/','이용약관','width=500,height=500,location=no,status=no,scrollbars=yes');">
                                이용약관
                            </button>
                        </form>
            </ul><br>

             <ul class="get-csv">
                 <form action="mdgup/" method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    <input type="text" name="id" size=35 class="frm_input required" size="35" maxLength="35" placeholder="사이트 아이디 입력"><br>
                    <input type="password" name="password" size=35 class="frm_input required" size="35" maxLength="35" placeholder="사이트 비밀번호 입력"><br>
                    <input type="file" name="file" size=5 class="frm_input required" size="20" maxLength="20" placeholder="CSV파일 업로드"style="margin: 0% 0% 0% 13%;"><br>
                    <label><input type="radio" name="site" value="melon"> Melon</label>
                    <label><input type="radio" name="site" value="genie"> Genie</label>
                    <label><input type="radio" name="site" value="bugs"> Bugs</label>
                    <label><input type="radio" name="site" value="flo"> FLO</label>
                    <label><input type="radio" name="site" value="vibe"> VIBE</label>
                    <input type="submit" value="  플레이 리스트 올리기  " class="btn_submit" style="padding: 10px; height: 40px; margin: 2% 0% 0% 50%;"><br><br>
                 </form>
             </ul>
              <ul class="recommend">
                <form action="re_result/" method="post" enctype="multipart/form-data" style="margin: 2% 0% 0% 40%;">
                    {%csrf_token%}
                    <input type="text" name="re_genre" size=5 class="frm_input required" size="5" maxLength="5" placeholder="장르입력">
                    <input type="submit" value=" 추천받기" class="btn_submit" style="padding: 10px; height: 40px;"><br>
                </form>
              </ul>
            </div> 
        </div>
    </div> 

    </main>

    </body>
    </html>

templates/music/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>It's time's music_move</title>
        <link rel="stylesheet" type="text/css" href="{% static 'music/default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/home.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/common.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/post.css' %}">
</head>
<body>
{% block nav %}

{% endblock %}

     <div class="nav">
        <div class="nav-area">
            <div class="nav-left">
                <a href="{% url 'music:SiteMain' %}" style="margin: 0% 200% 0% -200%">
                    <img  class="logo" src="{% static 'music/img/logo.png' %}" style="width: 96px; height: auto;" alt="logo">
                </a>
            </div>
            <div class="nav-right">
                <ul>

                   <li><a href="{% url 'music:user_guide' %}">사용 설명</a></li>
                    <li><a href="{% url 'music:post_list' %}">공유 게시판</a></li>
                </ul>
            </div>

        </div>
             <div class="nav-bar"></div>
    </div>

</body>
</html>

templates/music/mdg_list.html
{% extends "music/base.html" %}

{% block nav %}
    <section>

      <div class="board">
            성공적으로 변환되었습니다. 변환된 곡들의 리스트입니다.
        </div>

  <table border = '1' class ="table">
    <thead>
      <tr>
        <th>No.</th>
        <th>노래</th>
        <th>가수</th>
        <th>앨범</th>
        {% for mdg in mdgs|slice:":1" %}
        {% if mdg.site_code == 'M' %}
        <th>장르</th>
        {% endif %}
        {% endfor %}
      </tr>
    </thead>

    <tbody>

      {% for mdg in mdgs %}
       <tr>
          <td>{{forloop.counter}}</td>
          <td>{{mdg.song}}</td>
          <td>{{mdg.artist}}</td>
          <td>{{mdg.album}}</td>
           {% if mdg.site_code == 'M' %}
          <td>{{mdg.genre}}</td>
           {% endif %}
        </tr>
      {% endfor %}

     </p>
     <br>
    </tbody>

  </table>
      <div
         class="button-right"
         style="
            margin-left: 8%;
            width: 8%;
"
      >

                <a href="{% url 'music:mdg_delete' %}">메인으로</a>
        </div>




    </section>

{% endblock %}

templates/music/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>It's time's music_move</title>
</head>
<body>
<div class="container">
    <form method="POST" class="post-form">
        {%csrf_token%}

        <p>정말로 {{post.post_title}}를 삭제하시나요?</p>
        <input type="submit" class="save btn btn-default" value="Confirm"/>
    </form>
</div>
</body>
</html>

templates/music/post_detail.html
{% extends "music/base.html" %}

{% block nav %}
    <section>
        <div class="post-wrap">
        </div>
        <div class="post" id="post-title">

            {{ object.post_title }}

            <span id="post-date"> {{ object.post_date }}</span>
        </div>


        <div class="post" id="post-content">
            {{ object.post_contents|linebreaks }}
        </div>

        {% if post.post_file %}
            <div class="post">

                <div class="col-12 text-right">
                    <span>첨부파일 :&nbsp;</span>
                    <a href="{% url 'music:post_download' pk=post.pk %}">{{ post.post_filename|truncatechars:25 }}</a>
                </div>

            </div>
        {% endif %}





        <div class="post">
            {% if object.get_previous %}
                <a href="{{ object.get_previous.get_absolute_url }}"
                   title="이전 글">&larr; 이전글 : {{ object.get_previous }}</a>
            {% endif %}

            {% if object.get_next %}
                | <a href="{{ object.get_next.get_absolute_url }}" title="다음 글">{{ object.get_next }}: 다음글 &rarr;</a>
            {% endif %}
        </div>


        <div class="button-right"><a href="{% url 'music:post_delete' pk=post.pk %}">삭제</a></div>
        <div class="button-left"><a href="{% url 'music:post_update' pk=post.pk %}">수정</a></div>
        <div class="button-left"><a href="{% url 'music:post_list' %}">목록</a></div>


<div style="width:90%; height: 100px; margin: 3% 0 0 2%; border-bottom: 1px solid #58666e; "></div>


        <div class="comment-wrap">
            <form action="{% url 'music:comment_write' pk=post.pk %}" method="POST">
                {% csrf_token %}
                <input id="comment-id" type="char" name="writer" placeholder="name"/>

                <input id="comment-add" type="submit" value="댓글작성"/>
                <br><textarea id="comment-content" type="text" name="content"
                              placeholder="write your comments"></textarea>

            </form>

        </div>





        {% for comment in post.comments.all %}
            <div class="comment">

                <div class="comment-id" id="commented-id">
                    {{ comment.com_writer }}
                    <span id="commented-date">{{ comment.com_date }}</span>
                </div>

              <div class="commented-content">{{ comment.com_contents }}</div>
            </div>
        {% empty %}
            <div class="comment commented-content">No comments here yet</div>
        {% endfor %}

    </section>

{% endblock %}

templates/music/post_list.html
{% extends "music/base.html" %}

{% block nav %}
    <section>
        <div class="board">
            자유롭게 자신의 플레이리스트를 공유해주시길 바랍니다.
        </div>

        <table border='1' class="table">
            <thead>
            <tr>
                <th>No.</th>
                <th>태그</th>
                <th>제목</th>
                <th>작성자</th>
                <th>날짜</th>
                <!-- <th>추천수</th>
                <th>조회수</th> -->
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}

                <tr>

                    <td id="post_num">{{ post.post_id }}</td>
                    <td id="post_tag">{{ post.get_table_num_display }}</td>
                    <td><a href="{{ post.get_absolute_url }}">{{ post.post_title }}</a>({{ post.comments.count }})
                    </td>
                    <td>{{ post.writer }}</td>
                    <td>{{ post.post_date }}</td>
                    <!--
          <td>{{post.post_like}}</td>
          <td>{{post.post_hit}}</td> -->

                </tr>
            {% endfor %}
            </p>
            <br>
            </tbody>
        </table>


        <div class="button-right">
            <a href="{% url 'music:post_write' %}">글쓰기</a>
        </div>


        <div class="page">
            {% if page_obj.has_previous %}
                <div class="button-previous">

                    <a href="?page={{ page_obj.previous_page_number }}">이전</a>

                </div>
            {% endif %}

            <div class="page-num">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </div>
            {% if page_obj.has_next %}
                <div class="button-next">

                    <a href="?page={{ page_obj.next_page_number }}">다음</a>

                </div>
            {% endif %}
        </div>


    </section>

{% endblock %}

templates/music/re_result.html
{% extends "music/base.html" %}

{% block nav %}
    <section>

  <table border = '1' class ="table">
    <thead>
      <tr>
        <th>추천곡 리스트</th>
          {% for result in recmds %}
      </tr>
    </thead>
    <tbody>
       <tr>
            <td>{{ result }}</td>
        </tr>
       {% endfor %}
     </p>
    </tbody>

  </table>
          <div
         class="button-right"
         style="
            margin-left: 8%;
            width: 8%;
"
      >

  <a href="{% url 'music:SiteMain' %}">메인으로</a>
          </div>
    </section>

{% endblock %}